# Generated by Django 2.0.3 on 2018-03-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
