# Generated by Django 2.0.3 on 2018-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_sign_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
