# Generated by Django 2.0.3 on 2018-03-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180314_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
