# Generated by Django 2.0.3 on 2018-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20180314_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='sign',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
