# Generated by Django 2.0.3 on 2018-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20180314_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
