# Generated by Django 2.0.3 on 2018-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20180314_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
