# Generated by Django 2.0.3 on 2018-03-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_sign_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='profile_image',
        ),
    ]
